version: '3.9' 
services:
  fastapi:
    image: nperez02/clase_devops:myimagefastapiv5
    build: ./docker_fastapi
    ports:
      - '8080:80'
    depends_on:
      - mysql
  mysql:
    image: nperez02/clase_devops_mysql:myimagemysqlv2
    build: ./docker_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      # left side port = host | right side port = container
      - '3306:3306'
    volumes:
      - /home/$USER/datadir:/var/lib/mysql
    
